import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Introduce from "../components/Introduce";
import Experience from "../components/Experience";
import PersonalExperience from "../components/PersonalExperience";
import SkillAndEducation from "../components/SkillAndEducation";
import ToTheTopButton from "../UI&Layout/ToTheTopButton";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HyoKeunsResume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ToTheTopButton />
        <div className={styles.mainWrapper}>
          <Header />

          <Introduce />

          <Experience />
          <PersonalExperience />
          <SkillAndEducation />
        </div>
      </main>
    </div>
  );
}
