import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Introduce from "../components/Introduce";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HyoKeunsResume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <Header />
          <Introduce />
        </div>
      </main>
    </div>
  );
}
